-- MySQL Script generated by MySQL Workbench
-- Thu Jan 19 11:28:04 2023
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema curso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema curso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `curso` DEFAULT CHARACTER SET utf8mb4 ;
USE `curso` ;

-- -----------------------------------------------------
-- Table `curso`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`alunos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(12) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `curso`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`cursos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `curso`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`matricula` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data_mat` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `curso`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`professores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(12) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `curso`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`turmas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `curso_id` INT(11) NOT NULL,
  `professor_id` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `curso`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `curso`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
